### ISSUE TITLE
Django 4.0+ compatibility

### ISSUE THREAD

**Issue by Salomanuel** [jazzband/django-debug-toolbar#1593]
as soon as I add to `base.py` this:
```
INSTALLED_APPS += [
   'debug_toolbar',
]
```
I get `ImportError: cannot import name 'url' from 'django.conf.urls'`

apparently `django.conf.urls.url()` was deprecated in Django 3.0, and is removed in Django 4.0+    

is there any way to make Django Debug Toolbar work in Django 4.0+?

**Comment by tim-schilling** [comment]
What version of the toolbar are you using? Please share the full stacktrace.

**Comment by Salomanuel** [comment]
I'm very sorry, being new to Python and Wagtail I was following a tutorial (wagtail-for-beginners) and it was forcing  `django-debug-toolbar==2.1`
once I changed it to a current version, the problem got fixed

I'm very sorry for wasting your time!

**Comment by tim-schilling** [comment]
No worries, we've all been there and run into that scenario. Best of luck
to you!
