### ISSUE TITLE
django debug toolbar not working on django version 3.1

### ISSUE THREAD

**Issue by dimkoug** [jazzband/django-debug-toolbar#1420]
when i try to run django debug toolbar version 2  on django version 3.1  i get the following error

cannot import name 'get_safe_settings' from 'django.views.debug'

when i try to run the latest version of django debug toolbar on  the django version 3  

the debug toolbar not showing at all 

what is the propper  configuration ?

in my projects i use the following 

DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1']
INTERNAL_IPS = ('127.0.0.1', '0.0.0.0')

INSTALLED_APPS += (
    'debug_toolbar',
    'django_extensions',
)

MIDDLEWARE += (
    'debug_toolbar.middleware.DebugToolbarMiddleware',
)

DEBUG_TOOLBAR_PANELS = [
    'debug_toolbar.panels.versions.VersionsPanel',
    'debug_toolbar.panels.timer.TimerPanel',
    'debug_toolbar.panels.settings.SettingsPanel',
    'debug_toolbar.panels.headers.HeadersPanel',
    'debug_toolbar.panels.request.RequestPanel',
    'debug_toolbar.panels.sql.SQLPanel',
    'debug_toolbar.panels.staticfiles.StaticFilesPanel',
    'debug_toolbar.panels.templates.TemplatesPanel',
    'debug_toolbar.panels.cache.CachePanel',
    'debug_toolbar.panels.signals.SignalsPanel',
    'debug_toolbar.panels.logging.LoggingPanel',
    'debug_toolbar.panels.redirects.RedirectsPanel'
]

**Comment by matthiask** [comment]
The latest version of the debug toolbar is 3.2. Does it work if you upgrade?

**Comment by dimkoug** [comment]
@matthiask   with django 3.1.4  and djang-debug-toolbar 3.2   the toolbar not showing at all 

i get 

ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

i use python 3.9 on windows 10

**Comment by matthiask** [comment]
That's a different problem. Sorry, I can't help you there. When programming in Windows I always use the WSL2 environment.

**Comment by dimkoug** [comment]
@matthiask  i fixed that problem but still the toolbar not showing

**Comment by tim-schilling** [comment]
@dimkoug Can you[ try this](https://github.com/jazzband/django-debug-toolbar/issues/1336#issuecomment-705816317) to see if it helps you.

**Comment by dimkoug** [comment]
It dosent work

**Comment by tim-schilling** [comment]
Please provide more information regarding the errors and what you've tried. Error logs and stacktraces make debugging possible. If there are none, the more information we have on your setup, what you're doing/running and what you're seeing / not seeing is critical.

As a shot in the dark, you may also try moving the toolbar middleware further up your middlewares settings as suggested in the [docs](https://django-debug-toolbar.readthedocs.io/en/latest/installation.html).

**Comment by dimkoug** [comment]
# middleware

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'products.middleware.DoNotTrackMiddleware',
]

#toolbars

DEBUG_TOOLBAR_PANELS = [
    'debug_toolbar.panels.history.HistoryPanel',
    'debug_toolbar.panels.versions.VersionsPanel',
    'debug_toolbar.panels.timer.TimerPanel',
    'debug_toolbar.panels.settings.SettingsPanel',
    'debug_toolbar.panels.headers.HeadersPanel',
    'debug_toolbar.panels.request.RequestPanel',
    'debug_toolbar.panels.sql.SQLPanel',
    'debug_toolbar.panels.staticfiles.StaticFilesPanel',
    'debug_toolbar.panels.templates.TemplatesPanel',
    'debug_toolbar.panels.cache.CachePanel',
    'debug_toolbar.panels.signals.SignalsPanel',
    'debug_toolbar.panels.logging.LoggingPanel',
    'debug_toolbar.panels.redirects.RedirectsPanel',
    'debug_toolbar.panels.profiling.ProfilingPanel',
]

DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1']
INTERNAL_IPS = ('127.0.0.1', '0.0.0.0')

INSTALLED_APPS += (
    'debug_toolbar',
    'django_extensions',
)


#urls.py 

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    try:
        import debug_toolbar
        urlpatterns += [
            path('__debug__', include(debug_toolbar.urls)),
        ]
    except ImportError:
        pass


what other setting i have to configure ?

**Comment by tim-schilling** [comment]
Those settings look generally fine depending on what is actually happening. Did you try this workaround defined here: https://github.com/jazzband/django-debug-toolbar/issues/1336#issuecomment-705816317?

**Comment by dimkoug** [comment]
@tim-schilling  i did that , still dosen't show

**Comment by tim-schilling** [comment]
Sorry, you'll have to do some digging on your own to determine why it's not showing. I don't have enough information to suggest anything else right now.

**Comment by dimkoug** [comment]
@tim-schilling 

to reproduce the steps 

1 - install python 3.9 64bit to windows os
2. from cmd create a virtual enviroment and create a django project 
3. install django debug toolbar

**Comment by AlexElizard** [comment]
@dimkoug Can't reproduce your problem

I have:
* Django==3.1.4
* django-debug-toolbar==3.2
* Python 3.9.1
* Windows 10 Pro x64
* In the registry \HKEY_CLASSES_ROOT\.js\ContentType = text/javascript
```
# settings.py

if DEBUG:
    INSTALLED_APPS.append('debug_toolbar')
    MIDDLEWARE.append('debug_toolbar.middleware.DebugToolbarMiddleware')
    DEBUG_TOOLBAR_CONFIG = {
        'SHOW_TOOLBAR_CALLBACK': lambda request: True,
        'EXTRA_SIGNALS': [],
    }
    
# urls.py

if settings.DEBUG:
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))
```

**Comment by dimkoug** [comment]
Ok thanks a lot , fixed 

I created a new empty django project with one template view i   installed the latest version of django and debug-toolbar and the default settings of debug-toolbar and it worked 

versions i used 
python 3.7 on windows
django 3.1.4
django-debug-toolbar 3.2

and  In the registry \HKEY_CLASSES_ROOT\.js\ContentType = text/javascript

thanks @AlexElizard

**Comment by rahulkp220** [comment]
Thanks @AlexElizard , your post help me fix this issue on my end. Cheers 👍
