### ISSUE TITLE
'WSGIRequest' object has no attribute 'user'

### ISSUE THREAD

**Issue by danbruegge** [jazzband/django-debug-toolbar#550]
Hi,

i use django 1.6.2 and the django-debug-toolbar in version 1.0.1

The error occurs on a project i've updated from django 1.4.9 and djang-debug-toolbar 0.8.5.

If i remove the ddt from the settings.py/development.py all works fine. If enabled, the ddt also seems to be working but i get this error.

I can not figure out why the problem occurs. All my other projects are working fine with django 1.6.2 and ddj 1.0.1.

Here is my traceback: https://gist.github.com/haengebruegge/9052453

I also found an issue that has the same error message but with another reason: https://github.com/django-debug-toolbar/django-debug-toolbar/issues/399
