### ISSUE TITLE
AttributeError: 'module' object has no attribute 'getrusage'

### ISSUE THREAD

**Issue by yscumc** [jazzband/django-debug-toolbar#370]
I get the following error during page load:

```
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 92, in get_response
    response = middleware_method(request)
  File "C:\Python27\lib\site-packages\django_debug_toolbar-0.9.4-py2.7.egg\debug_toolbar\middleware.py", line 100, in process_request
    panel.process_request(request)
  File "C:\Python27\lib\site-packages\django_debug_toolbar-0.9.4-py2.7.egg\debug_toolbar\panels\timer.py", line 30, in process_request
    self._start_rusage = resource.getrusage(resource.RUSAGE_SELF)
AttributeError: 'module' object has no attribute 'getrusage'
[03/Apr/2013 13:11:08] "GET / HTTP/1.1" 500 62374
```

Using:
Windows 7
Django (1.5)
django-debug-toolbar (0.9.4) - commit 6f79f0b0ada69e1d95d97066ba78e0d18aeab3ba
django-session-security (2.0.3)
Genshi (0.7)
MySQL-python (1.2.4b4)
pep8 (1.4.5)
pytz (2013b)
pywin32 (218)
selenium (2.31.0)
Trac (1.0.1)
tracaccountmanager (0.4.3)
unittest-data-provider (1.0.0)

Also doesn't work on the 0.9.4 release... that's why I took the latest from the repo.
